import {
  Flower2,
  Laptop,
  Droplets,
  BookOpen,
  Dumbbell,
  Footprints,
  PenLine,
  Apple,
  Sunrise,
  Moon,
  HeartPulse,
  Coffee,
  Music,
  Camera,
  Sparkles,
  Brain,
  Palette,
  Wallet,
  Users,
  Bike,
  Bed,
  Sun,
  Sunset,
  CloudSun,
  Salad,
  GlassWater,
  Utensils,
  ChefHat,
  Pill,
  Stethoscope,
  Bath,
  ShowerHead,
  Shirt,
  Guitar,
  Mic,
  Headphones,
  Film,
  Gamepad2,
  Code,
  Terminal,
  Briefcase,
  GraduationCap,
  Languages,
  Calculator,
  NotebookPen,
  Mail,
  Phone,
  MessageCircle,
  Handshake,
  Gift,
  ShoppingBag,
  PiggyBank,
  Plane,
  Bus,
  Car,
  Leaf,
  TreePine,
  Sprout,
  Waves,
  Mountain,
  Snowflake,
  Recycle,
  Dog,
  Cat,
  Baby,
  Church,
  Timer,
  Target,
  Trophy,
  Star,
  Zap,
  Flame,
  Activity,
  Scale,
  Smile,
  PersonStanding,
  Feather,
  Anchor,
  type LucideIcon,
} from "lucide-react";

// Map both keyword slugs and legacy emoji → Lucide icons (iOS SF-Symbols feel).
const MAP: Record<string, LucideIcon> = {
  // slugs
  meditation: Flower2,
  work: Laptop,
  water: Droplets,
  book: BookOpen,
  gym: Dumbbell,
  walk: Footprints,
  journal: PenLine,
  food: Apple,
  morning: Sunrise,
  night: Moon,
  heart: HeartPulse,
  coffee: Coffee,
  music: Music,
  camera: Camera,
  spark: Sparkles,
  mind: Brain,
  art: Palette,
  money: Wallet,
  people: Users,
  bike: Bike,
  sleep: Bed,
  sun: Sun,
  sunset: Sunset,
  weather: CloudSun,
  salad: Salad,
  drink: GlassWater,
  meal: Utensils,
  cook: ChefHat,
  vitamin: Pill,
  health: Stethoscope,
  bath: Bath,
  shower: ShowerHead,
  laundry: Shirt,
  guitar: Guitar,
  sing: Mic,
  podcast: Headphones,
  movie: Film,
  game: Gamepad2,
  code: Code,
  terminal: Terminal,
  career: Briefcase,
  study: GraduationCap,
  language: Languages,
  budget: Calculator,
  notes: NotebookPen,
  email: Mail,
  call: Phone,
  chat: MessageCircle,
  network: Handshake,
  give: Gift,
  shopping: ShoppingBag,
  saving: PiggyBank,
  travel: Plane,
  commute: Bus,
  drive: Car,
  plant: Leaf,
  nature: TreePine,
  grow: Sprout,
  swim: Waves,
  hike: Mountain,
  cold: Snowflake,
  clean: Recycle,
  dog: Dog,
  cat: Cat,
  family: Baby,
  pray: Church,
  timer: Timer,
  target: Target,
  trophy: Trophy,
  star: Star,
  energy: Zap,
  streak: Flame,
  activity: Activity,
  weight: Scale,
  mood: Smile,
  stretch: PersonStanding,
  light: Feather,
  focus: Anchor,
  // legacy emoji → same icon
  "🧘": Flower2,
  "💻": Laptop,
  "💧": Droplets,
  "📖": BookOpen,
  "🏋️": Dumbbell,
  "🚶": Footprints,
  "✍️": PenLine,
  "🥗": Apple,
  "🌅": Sunrise,
  "🌙": Moon,
};

export const ICON_KEYS = [
  "meditation","work","water","book","gym","walk","journal","food",
  "morning","night","heart","coffee","music","camera","spark","mind",
  "art","money","people","bike",
  "sleep","sun","sunset","weather","salad","drink","meal","cook",
  "vitamin","health","bath","shower","laundry","guitar","sing","podcast",
  "movie","game","code","terminal","career","study","language","budget",
  "notes","email","call","chat","network","give","shopping","saving",
  "travel","commute","drive","plant","nature","grow","swim","hike",
  "cold","clean","dog","cat","family","pray","timer","target",
  "trophy","star","energy","streak","activity","weight","mood","stretch",
  "light","focus",
] as const;

export function HabitIcon({
  name,
  className = "size-4",
  strokeWidth = 1.75,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Icon = MAP[name] || Sparkles;
  return <Icon className={className} strokeWidth={strokeWidth} />;
}